import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
import os from 'node:os';
import { createPersonalizedPlan, normalizeObjectivePayload, refreshPlanPhase } from './plan-engine.mjs';
import { defaultPlanPreferences, normalizePlanPreferences, applyCollaborativePlanDesign, planDiff, createPlanVersion, weeklyReview, preferenceRecommendation } from './plan-collaboration.mjs';

const bundledState = new URL('../data/state.json', import.meta.url);
const tmpState = path.join(os.tmpdir(), 'coach-coros-state.json');
async function readState(){try{return JSON.parse(await readFile(tmpState,'utf8'));}catch{const initial=JSON.parse(await readFile(bundledState,'utf8'));await writeFile(tmpState,JSON.stringify(initial,null,2),'utf8');return initial;}}
async function saveState(state){await writeFile(tmpState,JSON.stringify(state,null,2),'utf8');}
function localDateIso(){return new Intl.DateTimeFormat('en-CA',{timeZone:process.env.APP_TIMEZONE||'Europe/Paris',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());}
function daysToDate(date){if(!date)return null;const t=new Date(`${localDateIso()}T00:00:00Z`),d=new Date(`${date}T00:00:00Z`);return Math.max(0,Math.ceil((d-t)/86400000));}
function addDaysIso(iso,days){const d=new Date(`${iso}T12:00:00Z`);d.setUTCDate(d.getUTCDate()+days);return d.toISOString().slice(0,10);}
function dayLabel(iso){return ['Dim','Lun','Mar','Mer','Jeu','Ven','Sam'][new Date(`${iso}T12:00:00Z`).getUTCDay()];}
function json(body,status=200){return Response.json(body,{status,headers:{'cache-control':'no-store'}});}
function prepareState(state){state.objectives||=[];state.plans||=[];state.activities||=[];state.feedback||=[];state.coachMessages||=[];state.adaptationProposals||=[];state.planProposals||=[];state.planVersions||=[];state.deletedObjectiveIds||=[];return state;}
function legacySessionTemplate(dateIso,plan){const wd=new Date(`${dateIso}T12:00:00Z`).getUTCDay(),start=new Date(`${plan.startDate||dateIso}T12:00:00Z`),cur=new Date(`${dateIso}T12:00:00Z`),wi=Math.max(0,Math.floor((cur-start)/(7*86400000))),long=Math.min(95,60+wi*5),easy=Math.min(55,40+wi*3),base={id:`sess-${dateIso.replaceAll('-','')}`,date:dateIso,day:dayLabel(dateIso),status:'planned',generatedBy:'adaptive-plan-v1'};if(wd===1)return{...base,sport:'Repos',title:'Repos / mobilité',duration:'20 min optionnel',details:'Mobilité douce uniquement si utile.',zone:1,zoneLabel:'Repos',hrTarget:'—',rpeTarget:'1/10',paceTarget:'—'};if(wd===2)return{...base,sport:'Course à pied',title:'Séance spécifique',duration:'≈ 60 min',details:'Séance spécifique héritée du plan initial. Reconstruis le plan pour passer au moteur collaboratif.',zone:3,zoneLabel:'Z3 → Z4',hrTarget:'Contrôlé',rpeTarget:'5–6/10',paceTarget:'Selon objectif'};if(wd===3)return{...base,sport:'Gravel / vélo',title:'Récupération active',duration:'40–50 min',details:'Très facile.',zone:1,zoneLabel:'Z1',hrTarget:'Très facile',rpeTarget:'1–2/10',paceTarget:'FC prioritaire'};if(wd===4)return{...base,sport:'Course à pied',title:'Endurance fondamentale',duration:`${easy}–${easy+5} min`,details:'Conversation fluide.',zone:2,zoneLabel:'Z2',hrTarget:'Endurance facile',rpeTarget:'2–3/10',paceTarget:'Libre'};if(wd===5)return{...base,sport:'Vélo + renfo',title:'Endurance facile + renfo',duration:'60–75 min + 10 min',details:'Renforcement léger sans douleur.',zone:1,zoneLabel:'Z1 → Z2',hrTarget:'Facile',rpeTarget:'2–3/10',paceTarget:'—'};if(wd===6)return{...base,sport:'Course à pied',title:'Sortie longue facile',duration:`${long}–${long+5} min`,details:'Reste patient et régulier.',zone:2,zoneLabel:'Z2',hrTarget:'Endurance facile',rpeTarget:'2–3/10',paceTarget:'Libre'};return{...base,sport:'Gravel',title:'Endurance aérobie',duration:'1 h 30–2 h',details:'Volume sans impact à intensité facile.',zone:2,zoneLabel:'Z2',hrTarget:'Endurance facile',rpeTarget:'2–3/10',paceTarget:'—'};}
function ensurePlanCoverage(state,horizonDays=14){const objective=state.objectives.find(o=>o.status==='active'),plan=objective?state.plans.find(p=>p.id===objective.planId):state.plans.find(p=>p.status==='active');if(!plan)return false;if(/personalized-plan-v[23]/.test(plan.generatedBy||''))return refreshPlanPhase(plan,localDateIso());plan.sessions||=[];const today=localDateIso(),horizon=addDaysIso(today,horizonDays),end=objective?.date&&objective.date<horizon?objective.date:horizon,dates=new Set(plan.sessions.map(s=>s.date).filter(Boolean));let changed=false;for(let d=today;d<=end;d=addDaysIso(d,1))if(!dates.has(d)){plan.sessions.push(legacySessionTemplate(d,plan));dates.add(d);changed=true;}plan.sessions.sort((a,b)=>String(a.date||'').localeCompare(String(b.date||'')));return changed;}
function activeContext(state){const activeObjective=state.objectives.find(o=>o.status==='active')||null,activePlan=activeObjective?state.plans.find(p=>p.id===activeObjective.planId)||null:state.plans.find(p=>p.status==='active')||null,todayIso=localDateIso(),todaySession=activePlan?.sessions?.find(s=>s.date===todayIso)||null,latestActivity=[...state.activities].sort((a,b)=>String(b.date||'').localeCompare(String(a.date||'')))[0]||null;return{activeObjective,activePlan,todaySession,latestActivity,todayIso};}
function findSession(state,id){for(const plan of state.plans){const session=(plan.sessions||[]).find(s=>s.id===id);if(session)return{plan,session};}return null;}
function dashboard(state){const ctx=activeContext(state);return{...state,activeObjective:ctx.activeObjective,activePlan:ctx.activePlan,todaySession:ctx.todaySession,latestActivity:ctx.latestActivity,meta:{today:ctx.todayIso,daysToObjective:daysToDate(ctx.activeObjective?.date),corosMode:process.env.COROS_MODE||'demo',openAiMode:process.env.OPENAI_API_KEY?'connected':'demo',persistence:'temporary-vercel+device-continuity',adaptivePlan:true,planEngine:ctx.activePlan?.generatedBy||'none'}};}
function activateObjectiveAndPlan(state,objective,plan){for(const o of state.objectives)if(o.id!==objective.id&&o.status==='active')o.status='planned';for(const p of state.plans)if(p.id!==plan?.id&&p.status==='active')p.status='paused';objective.status='active';if(plan)plan.status='active';}
function planFor(state,id){return state.plans.find(p=>p.id===id)||null;}
function objectiveForPlan(state,plan){return state.objectives.find(o=>o.id===plan?.objectiveId)||state.objectives.find(o=>o.planId===plan?.id)||null;}
function collaborationPayload(state,plan){const objective=objectiveForPlan(state,plan),prefs=normalizePlanPreferences(plan.preferences||{},objective||{},plan.preferences||defaultPlanPreferences(objective||{},plan)),versions=state.planVersions.filter(v=>v.planId===plan.id).sort((a,b)=>b.version-a.version).slice(0,20),pending=state.planProposals.filter(p=>p.planId===plan.id&&p.status==='proposed').sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt))),today=localDateIso(),start=plan.startDate||today,currentWeek=Math.max(0,Math.floor((new Date(`${today}T12:00:00Z`)-new Date(`${start}T12:00:00Z`))/(7*86400000))),reviewedWeeks=new Set(state.planProposals.filter(p=>p.planId===plan.id&&p.type==='weekly-review').map(p=>p.reviewWeekIndex)),dueWeek=Math.max(0,currentWeek-1),weeklyReviewDue=currentWeek>0&&!reviewedWeeks.has(dueWeek);return{objective,preferences:prefs,versions,pendingProposals:pending,weeklyReviewDue,dueWeekIndex:dueWeek,designSummary:plan.designSummary||null};}
function adaptationFor(session,reason,note=''){const signal=`${reason||''} ${note||''}`.toLowerCase(),proposed={...session};delete proposed.completedAt;proposed.status='planned';let explanation='On garde l’objectif de la séance mais on réduit le coût de fatigue.';if(/gêne|douleur|pain|bless/.test(signal)){Object.assign(proposed,{sport:'Repos actif / mobilité',title:'Récupération sans impact',duration:'20–30 min',details:'Mobilité douce ou marche uniquement si la gêne reste légère. Arrête si la douleur augmente.',zone:1,zoneLabel:'Très facile',hrTarget:'—',rpeTarget:'1–2/10',paceTarget:'—'});explanation='Une gêne prime sur la performance : on retire l’impact et l’intensité aujourd’hui.';}else if(/peu de temps|temps|court|30 min|press/.test(signal)){proposed.duration='30 min';proposed.details=/blocs|allure|seuil/i.test(session.title)?'10 min facile + 2×5 min au stimulus principal, récup 3 min + retour au calme.':'5 min très facile + 20 min dans la zone cible + 5 min de retour au calme.';explanation='On conserve le stimulus principal en compressant la séance.';}else if(/jambes lourdes|lourdes|courbature/.test(signal)){Object.assign(proposed,{sport:'Gravel / vélo',title:'Décrassage jambes lourdes',duration:'35–45 min',details:'Pédalage très souple, sans force.',zone:1,zoneLabel:'Z1',hrTarget:'Très facile',rpeTarget:'1–2/10',paceTarget:'FC prioritaire'});explanation='On remplace l’impact par du mouvement facile.';}else if(/fatigu|sommeil|épuis|crevé/.test(signal)){Object.assign(proposed,{sport:'Gravel / vélo',title:'Récupération active',duration:'30–40 min',details:'Très facile. Si la fatigue est générale, transforme en repos.',zone:1,zoneLabel:'Z1',hrTarget:'Très facile',rpeTarget:'1–2/10',paceTarget:'FC prioritaire'});explanation='La fatigue du jour justifie de réduire nettement la charge.';}else if(/très bien|super|forme|excellent/.test(signal)){proposed.details=`${session.details||''} Si les sensations restent excellentes, ajoute seulement 5–10 min très faciles à la fin.`.trim();explanation='Même avec de très bonnes sensations, on évite la surcharge.';}return{proposed,explanation};}
async function coachReply(state,userMessage){ensurePlanCoverage(state);const{activeObjective,activePlan,todaySession,latestActivity,todayIso}=activeContext(state);if(!process.env.OPENAI_API_KEY)return`Mode démo : j'ai reçu « ${userMessage} ». Ton objectif actif est « ${activeObjective?.title||'aucun objectif actif'} ».`;const corosLive=(process.env.COROS_MODE||'demo')!=='demo',context={athlete:state.athlete,heartRateZones:state.heartRateZones,metrics:corosLive?state.metrics:null,dataFreshness:{today:todayIso,corosLive},activeObjective,activePlan,todaySession,latestActivity,recentFeedback:state.feedback.slice(0,8)};const response=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{authorization:`Bearer ${process.env.OPENAI_API_KEY}`,'content-type':'application/json'},body:JSON.stringify({model:process.env.OPENAI_MODEL||'gpt-5.6-luna',reasoning:{effort:'low'},input:`Tu es Coach COROS, coach d'endurance prudent. Contexte JSON:\n${JSON.stringify(context)}\nMessage de l'athlète: ${userMessage}\nRéponds en français, de façon concise et pratique. Prévention des blessures avant la performance. Le plan est collaboratif : explique les compromis au lieu d'exécuter aveuglément une demande risquée.`})});if(!response.ok)throw new Error(`OpenAI API ${response.status}: ${await response.text()}`);const data=await response.json();return(data.output||[]).flatMap(i=>i.content||[]).filter(i=>i.type==='output_text').map(i=>i.text).join('\n').trim()||'Pas de réponse.';}
async function buildDesignedPlan({state,objective,fitnessContext=null,existingPlan=null,preferences=null}){const base=await createPersonalizedPlan({state,objective,fitnessContext,existingPlan}),designed=applyCollaborativePlanDesign(base,objective,fitnessContext?{...state,metrics:fitnessContext.metrics||state.metrics,heartRateZones:fitnessContext.heartRateZones||state.heartRateZones}:state,preferences||existingPlan?.preferences||{});designed.generationMode=base.generationMode;designed.generatedBy='personalized-plan-v3';return designed;}
async function proposalCandidate({state,objective,plan,preferences,fitnessContext=null}){return buildDesignedPlan({state,objective:{...objective,sessionsPerWeek:preferences.sessionsPerWeek,preferredLongDay:preferences.preferredLongDay},fitnessContext,existingPlan:plan,preferences});}

export default {async fetch(request){try{const url=new URL(request.url),route=url.searchParams.get('path')||'',method=request.method.toUpperCase(),state=prepareState(await readState());
if(method==='GET'&&route==='dashboard'){if(ensurePlanCoverage(state))await saveState(state);return json(dashboard(state));}
if(method==='GET'&&route==='coros/status')return json({mode:process.env.COROS_MODE||'demo',connected:Boolean(process.env.COROS_ACCESS_TOKEN)});
if(method==='POST'&&route==='objectives'){const payload=await request.json(),normalized=normalizeObjectivePayload(payload);if(!normalized.title)return json({error:"Nom de l'objectif requis"},400);if(normalized.date&&normalized.date<localDateIso())return json({error:'La date cible doit être dans le futur.'},400);if(/course|trail/i.test(normalized.sport)&&!normalized.distanceKm)return json({error:'Distance requise pour un objectif de course ou trail.'},400);const objective={id:`obj-${crypto.randomUUID()}`,...normalized,status:'proposed',activateAfterAcceptance:normalized.activateNow,planId:null,createdAt:new Date().toISOString()},preferences=defaultPlanPreferences(objective,{}),plan=await buildDesignedPlan({state,objective,fitnessContext:payload._fitnessContext||null,preferences});objective.planId=plan.id;plan.objectiveId=objective.id;plan.status='proposed';createPlanVersion(state,plan,{reason:'Création du plan',summary:plan.designSummary?.rationale||''});state.objectives.unshift(objective);state.plans.unshift(plan);await saveState(state);return json({ok:true,objective,plan,generation:{engine:'personalized-plan-v3',mode:plan.generationMode},proposal:true},201);}
let match=route.match(/^objectives\/([^/]+)\/accept-plan$/);if(method==='POST'&&match){const objective=state.objectives.find(o=>o.id===decodeURIComponent(match[1]));if(!objective)return json({error:'Objectif introuvable'},404);const plan=planFor(state,objective.planId);if(!plan)return json({error:'Plan introuvable'},404);activateObjectiveAndPlan(state,objective,plan);objective.acceptedAt=new Date().toISOString();plan.acceptedAt=objective.acceptedAt;await saveState(state);return json({ok:true,activeObjective:objective,activePlan:plan});}
match=route.match(/^objectives\/([^/]+)\/regenerate$/);if(method==='POST'&&match){const objective=state.objectives.find(o=>o.id===decodeURIComponent(match[1]));if(!objective)return json({error:'Objectif introuvable'},404);const oldPlan=planFor(state,objective.planId),payload=await request.json().catch(()=>({})),newPlan=await buildDesignedPlan({state,objective,fitnessContext:payload._fitnessContext||null,existingPlan:oldPlan,preferences:oldPlan?.preferences}),diff=planDiff(oldPlan,newPlan);Object.assign(oldPlan,newPlan,{id:oldPlan.id,objectiveId:objective.id,status:oldPlan.status});const version=createPlanVersion(state,oldPlan,{reason:'Reconstruction demandée par l’athlète',summary:oldPlan.designSummary?.rationale||'',diff});await saveState(state);return json({ok:true,objective,plan:oldPlan,version,diff,generation:{engine:'personalized-plan-v3',mode:oldPlan.generationMode}});}
match=route.match(/^objectives\/([^/]+)$/);if(method==='DELETE'&&match){const id=decodeURIComponent(match[1]),idx=state.objectives.findIndex(o=>o.id===id);if(idx<0)return json({error:'Objectif introuvable'},404);const[objective]=state.objectives.splice(idx,1),pidx=state.plans.findIndex(p=>p.id===objective.planId),plan=pidx>=0?state.plans.splice(pidx,1)[0]:null;state.deletedObjectiveIds.push(id);const sessionIds=new Set((plan?.sessions||[]).map(s=>s.id));state.adaptationProposals=state.adaptationProposals.filter(p=>!sessionIds.has(p.sessionId));state.planProposals=state.planProposals.filter(p=>p.planId!==plan?.id);state.planVersions=state.planVersions.filter(v=>v.planId!==plan?.id);if(objective.status==='active'){for(const o of state.objectives)if(o.status==='active')o.status='planned';for(const p of state.plans)if(p.status==='active')p.status='paused';}await saveState(state);return json({ok:true,deletedObjectiveId:id,deletedPlanId:plan?.id||null,noActiveObjective:objective.status==='active'});}
match=route.match(/^objectives\/([^/]+)\/activate$/);if(method==='POST'&&match){const objective=state.objectives.find(o=>o.id===decodeURIComponent(match[1]));if(!objective)return json({error:'Objectif introuvable'},404);const plan=planFor(state,objective.planId);activateObjectiveAndPlan(state,objective,plan);await saveState(state);return json({ok:true,activeObjective:objective,activePlan:plan});}
match=route.match(/^objectives\/([^/]+)\/complete$/);if(method==='POST'&&match){const objective=state.objectives.find(o=>o.id===decodeURIComponent(match[1]));if(!objective)return json({error:'Objectif introuvable'},404);objective.status='completed';objective.completedAt=new Date().toISOString();const plan=planFor(state,objective.planId);if(plan)plan.status='completed';await saveState(state);return json({ok:true,objective});}
match=route.match(/^plans\/([^/]+)\/collaboration$/);if(method==='GET'&&match){const plan=planFor(state,decodeURIComponent(match[1]));if(!plan)return json({error:'Plan introuvable'},404);return json({ok:true,...collaborationPayload(state,plan)});}
match=route.match(/^plans\/([^/]+)\/preferences\/propose$/);if(method==='POST'&&match){const plan=planFor(state,decodeURIComponent(match[1]));if(!plan)return json({error:'Plan introuvable'},404);const objective=objectiveForPlan(state,plan),payload=await request.json(),current=normalizePlanPreferences(plan.preferences||{},objective,plan.preferences||{}),next=normalizePlanPreferences(payload.preferences||payload,objective,current),recommendation=preferenceRecommendation(current,next,payload._fitnessContext||{}),candidate=await proposalCandidate({state,objective,plan,preferences:next,fitnessContext:payload._fitnessContext||null}),diff=planDiff(plan,candidate),proposal={id:`pp-${crypto.randomUUID()}`,planId:plan.id,objectiveId:objective.id,type:'preferences',status:'proposed',createdAt:new Date().toISOString(),currentPreferences:current,proposedPreferences:next,recommendation,diff,candidatePlan:candidate,userNote:String(payload.userNote||next.athleteNote||'')};state.planProposals.unshift(proposal);await saveState(state);return json({ok:true,proposal:{...proposal,candidatePlan:undefined}});}
match=route.match(/^plans\/([^/]+)\/weekly-review$/);if(method==='POST'&&match){const plan=planFor(state,decodeURIComponent(match[1]));if(!plan)return json({error:'Plan introuvable'},404);const objective=objectiveForPlan(state,plan),payload=await request.json().catch(()=>({})),review=weeklyReview(state,objective,plan,payload._fitnessContext||null),candidate=await proposalCandidate({state,objective,plan,preferences:review.proposedPreferences,fitnessContext:payload._fitnessContext||null}),diff=planDiff(plan,candidate),proposal={...review,reviewWeekIndex:review.week.index-1,diff,candidatePlan:candidate};state.planProposals.unshift(proposal);await saveState(state);return json({ok:true,proposal:{...proposal,candidatePlan:undefined}});}
match=route.match(/^plans\/([^/]+)\/proposals\/([^/]+)\/apply$/);if(method==='POST'&&match){const plan=planFor(state,decodeURIComponent(match[1]));if(!plan)return json({error:'Plan introuvable'},404);const proposal=state.planProposals.find(p=>p.id===decodeURIComponent(match[2])&&p.planId===plan.id);if(!proposal)return json({error:'Proposition introuvable'},404);if(proposal.status!=='proposed')return json({error:'Cette proposition a déjà été traitée.'},409);const candidate=proposal.candidatePlan;if(!candidate)return json({error:'Plan proposé indisponible'},409);const diff=proposal.diff||planDiff(plan,candidate),preservedPast=(plan.sessions||[]).filter(s=>s.date<localDateIso());Object.assign(plan,candidate,{id:plan.id,objectiveId:plan.objectiveId,status:plan.status,sessions:[...preservedPast,...(candidate.sessions||[]).filter(s=>s.date>=localDateIso())].sort((a,b)=>a.date.localeCompare(b.date))});proposal.status='applied';proposal.appliedAt=new Date().toISOString();delete proposal.candidatePlan;const reason=proposal.type==='weekly-review'?'Adaptation après bilan hebdomadaire':'Ajustement demandé par l’athlète',version=createPlanVersion(state,plan,{reason,summary:proposal.summary||proposal.recommendation?.summary||'',diff});await saveState(state);return json({ok:true,plan,proposal,version,diff});}
match=route.match(/^plans\/([^/]+)\/proposals\/([^/]+)\/reject$/);if(method==='POST'&&match){const proposal=state.planProposals.find(p=>p.id===decodeURIComponent(match[2])&&p.planId===decodeURIComponent(match[1]));if(!proposal)return json({error:'Proposition introuvable'},404);proposal.status='rejected';proposal.rejectedAt=new Date().toISOString();delete proposal.candidatePlan;await saveState(state);return json({ok:true,proposal});}
if(method==='POST'&&route==='plans/continuity/restore'){const payload=await request.json(),deleted=new Set(Array.isArray(payload.deletedObjectiveIds)?payload.deletedObjectiveIds.slice(0,100):[]);if(deleted.size){state.objectives=state.objectives.filter(o=>!deleted.has(o.id));const validIds=new Set(state.objectives.map(o=>o.planId));state.plans=state.plans.filter(p=>validIds.has(p.id));state.deletedObjectiveIds=[...new Set([...state.deletedObjectiveIds,...deleted])];}for(const objective of(Array.isArray(payload.objectives)?payload.objectives.slice(0,20):[])){const idx=state.objectives.findIndex(o=>o.id===objective.id);if(idx>=0)state.objectives[idx]=objective;else state.objectives.unshift(objective);}for(const plan of(Array.isArray(payload.plans)?payload.plans.slice(0,20):[])){const idx=state.plans.findIndex(p=>p.id===plan.id);if(idx>=0)state.plans[idx]=plan;else state.plans.unshift(plan);}if(Array.isArray(payload.planVersions))state.planVersions=payload.planVersions.slice(0,80);if(Array.isArray(payload.planProposals))state.planProposals=payload.planProposals.filter(p=>p.status!=='proposed').slice(0,80);await saveState(state);return json({ok:true,restored:true});}
match=route.match(/^sessions\/([^/]+)\/complete$/);if(method==='POST'&&match){const found=findSession(state,decodeURIComponent(match[1]));if(!found)return json({error:'Séance introuvable'},404);found.session.status='completed';found.session.completedAt=new Date().toISOString();await saveState(state);return json({ok:true,session:found.session});}
match=route.match(/^sessions\/([^/]+)\/adapt$/);if(method==='POST'&&match){const id=decodeURIComponent(match[1]),found=findSession(state,id);if(!found)return json({error:'Séance introuvable'},404);if(found.session.status==='completed')return json({error:'Une séance terminée ne peut plus être adaptée.'},409);const payload=await request.json(),{proposed,explanation}=adaptationFor(found.session,payload.reason,payload.note),proposal={id:crypto.randomUUID(),sessionId:id,createdAt:new Date().toISOString(),status:'proposed',reason:explanation,userReason:payload.reason||'',note:payload.note||'',original:{title:found.session.title,sport:found.session.sport,duration:found.session.duration,hrTarget:found.session.hrTarget,rpeTarget:found.session.rpeTarget},proposed:{title:proposed.title,sport:proposed.sport,duration:proposed.duration,details:proposed.details,zone:proposed.zone,zoneLabel:proposed.zoneLabel,hrTarget:proposed.hrTarget,rpeTarget:proposed.rpeTarget,paceTarget:proposed.paceTarget}};state.adaptationProposals.unshift(proposal);await saveState(state);return json({ok:true,proposal});}
match=route.match(/^sessions\/([^/]+)\/adapt\/apply$/);if(method==='POST'&&match){const id=decodeURIComponent(match[1]),found=findSession(state,id);if(!found)return json({error:'Séance introuvable'},404);const payload=await request.json(),proposal=state.adaptationProposals.find(p=>p.id===payload.proposalId&&p.sessionId===id);if(!proposal)return json({error:'Proposition introuvable'},404);const before={...found.plan,sessions:(found.plan.sessions||[]).map(s=>({...s}))};Object.assign(found.session,proposal.proposed,{adaptedAt:new Date().toISOString(),adaptedFrom:{...found.session},adaptationReason:proposal.userReason||proposal.reason});proposal.status='applied';proposal.appliedAt=new Date().toISOString();createPlanVersion(state,found.plan,{reason:'Adaptation d’une séance',summary:proposal.reason,diff:planDiff(before,found.plan)});await saveState(state);return json({ok:true,session:found.session,proposal});}
if(method==='POST'&&route==='feedback'){const payload=await request.json();for(const key of['rpe','legs','cardio','pain','couldContinue'])if(payload[key]===undefined||payload[key]==='')return json({error:`Champ manquant: ${key}`},400);const{activeObjective,activePlan,latestActivity}=activeContext(state),activityId=payload.activityId||latestActivity?.id||null,sessionId=payload.sessionId||null;if(!activityId&&!sessionId)return json({error:'Aucune activité ou séance à commenter'},400);const item={id:crypto.randomUUID(),at:new Date().toISOString(),activityId,sessionId,objectiveId:activeObjective?.id||null,planId:activePlan?.id||null,...payload};state.feedback.unshift(item);await saveState(state);return json({ok:true,feedback:item},201);}
if(method==='POST'&&route==='coach'){const{message}=await request.json();if(!message?.trim())return json({error:'Message vide'},400);const reply=await coachReply(state,message.trim());state.coachMessages.unshift({at:new Date().toISOString(),text:reply});await saveState(state);return json({reply});}
return json({error:`Route API inconnue: ${route}`},404);}catch(error){console.error('router',error);return json({error:error?.message||'Erreur serveur'},500);}}};
